# version: "3.9"   # optional, since Compose v2 doesn’t require version

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://nandish1729_db_user:dPszBg2xnwmnQXNW@blogapp.ztflouk.mongodb.net/blog-app?retryWrites=true&w=majority
    depends_on:
      - mongo
